### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by qn757275373** [youmi-zym/GO-SLAM#1]
Thank you very much for your significant contribution in the nerf-slam. I am also a researcher in this field and hope to have a thorough understanding of some details of the paper through reviewing your source code, so as to gain some inspiration. May I know when I can see your source code.

**Comment by youmi-zym** [comment]
Hi, 
Thanks for your interest! We will upload the code within 1 month and update once the code is available.  You can subscribe to this issue for the progress.

Best,
Youmin

**Comment by youmi-zym** [comment]
Hi, 

Code is available, enjoy!

Best,
Youmin

**Comment by phamquandung** [comment]
Hi @youmi-zym,

Thank you for sharing your code to the users.

I tried you code and I encountered some errors. I finally solved in. I would like to give some comments on this so other users may save their time. Please add eigen and lietorch in thridparty folder. Also, in the setup.py, please change the code line 12-17 as:
`            sources=[
                'src/lib/droid.cpp', 
                'src/lib/droid_kernels.cu',
                'src/lib/correlation_kernels.cu',
                'src/lib/altcorr_kernel.cu',
            ],`

Thank you!

**Comment by youmi-zym** [comment]
Hi @phamquandung ,

Thanks for the advice. Issue solved!

Best,
Youmin
