### ISSUE TITLE
results visualization

### ISSUE THREAD

**Issue by sx123456123** [youmi-zym/GO-SLAM#10]
Hello, how can I visual trajectory and 3D models?

**Comment by youmi-zym** [comment]
Hi,

You can visualize the trajectory and point cloud by modifying  [this](https://github.com/youmi-zym/GO-SLAM/blob/main/src/slam.py#L382) to:

`mp.Process(target=self.visualizing, args=(5, not dont_run))`

It will increase the GPU memory consumption a little bit. 

For the 3D models, you can use MeshLab or open3d to visualize the predicted mesh stored at OUT_DIR.

Best,
Youmin
