### ISSUE TITLE
Replica data failed to run

### ISSUE THREAD

**Issue by wangt-tong** [youmi-zym/GO-SLAM#16]
Thank you to the author for providing such a great open source project.
After configuring my environment according to the tutorial, try running the  Replica demo.
Download the data from [Google Drive],follow:
![2023-11-13 17-05-17 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/54926133/523bd30c-64b2-436a-9a5f-179b853c222b)
However, when processing data in the code, it is necessary to obtain traj.txt from the original data, and there are no related files in the downloaded dataset
![2023-11-13 17-10-05 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/54926133/73c4aceb-62f1-44aa-ba48-d1aa76d39dcb)
I really want to know how the author got started...
Looking forward to the author's reply.Thinks

**Comment by youmi-zym** [comment]
Hi,

You can download the RGB, Depth, and poses.txt with [this script](https://drive.google.com/file/d/1c4AJexdLzoMV5-mRGqtoxBqJpIwERx0O/view?usp=drive_link), and organize the dataset as we described at the Readme file.

Best, 
Youmin

**Comment by wangt-tong** [comment]
It's an honor to receive your reply. 
I tried to download the dataset and configure it, and now it runs successfully. 
However, due to my GPU: RTX3060 12G not running properly, I am ready to try replacing it with a better GPU.

**Comment by wangt-tong** [comment]
Can you provide the data package for scannet, as its data is more suitable for the project I am researching
