### ISSUE TITLE
Environment Setup Issues: Missing Packages and Typo in environment.yaml

### ISSUE THREAD

**Issue by DilaraYi** [youmi-zym/GO-SLAM#18]
Thank you for sharing this great project! 
Following the setup instructions, I encountered issues with missing packages like "pytorch-scatter". Despite attempting to install them manually using conda, I consistently encountered unresolvable incompatibilities.
Additionally, I noticed a minor typo in the environment.yaml file on line 201:

>     - PyOpenGL-acclerate==3.1.6
I believe the correct spelling is "accelerate". Would it be possible to seek your advice on resolving these matters, or could you provide an updated environment file to address these issues?

Thank you for your time and consideration.

**Comment by AndrewTKent** [comment]
Hello, 

Yes just correct the spelling lol, its supposed to be PyOpenGL-accelerate==3.1.6 

Also install pytorch scatter by doing the following after creating the go-slam venv

conda install pytorch-scatter -c pyg

Best, 
Andrew
