### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by phamquandung** [youmi-zym/GO-SLAM#2]
Dear authors,

After installing dependencies, I tried to run evaluation. However, I encounter this issue as below figure. Could you please help me solve this problem?

Thank you!

![Screenshot from 2023-10-18 10-56-42](https://github.com/youmi-zym/GO-SLAM/assets/28943896/7345767b-aad1-45cf-87cd-ac8eeca43df6)

**Comment by phamquandung** [comment]
I tried to re-install and it worked fine now

**Comment by youmi-zym** [comment]
Hi,

Cool! If no other problems, I will close this issue.

Best,
Youmin
