### ISSUE TITLE
Is loop closure not enabled in RGB-D setting? 

### ISSUE THREAD

**Issue by cmh1027** [youmi-zym/GO-SLAM#23]
I just noticed that unlike replica_mono.yaml, there's no enable_loop item in replica.yaml. Is this intentional?

**Comment by youmi-zym** [comment]
Hi,

The loop closure is enabled in any mode. Without an extra claim, the config file will be inherited [here](https://github.com/youmi-zym/GO-SLAM/blob/main/configs/go_slam.yaml#L59). 

Best,
Youmin
