### ISSUE TITLE
Where can I find the code using backend.loop_radius?

### ISSUE THREAD

**Issue by cmh1027** [youmi-zym/GO-SLAM#24]
I'm struggling with finding the code part where finds high covisibility between local keyframes and historical keyframes to find loop like mentioned in the paper. However, I can't find the corresponding code with that. Is it not included in the code yet?

**Comment by youmi-zym** [comment]
Hi,

You can find it [here](https://github.com/youmi-zym/GO-SLAM/blob/main/configs/go_slam.yaml#L73). All configs are inherited from goslam.yaml.

Best,
Youmin

**Comment by cmh1027** [comment]
How about the code part, not a config file?

**Comment by lvmingzhe** [comment]
same question.

**Comment by lvmingzhe** [comment]
https://github.com/youmi-zym/GO-SLAM/blob/5f11b52c22aaa33b0711fa85fdadb8300f11b6c1/src/backend.py#L143

Maybe ```self.backend_radius``` here should be ```self.backend.loop_radius```

**Comment by lvmingzhe** [comment]
is this all the strategy to decide when droid-slam could find a loop?
I`m not sure how it works especially in line ```84```
can you explain the basic idea to me? Thx

https://github.com/youmi-zym/GO-SLAM/blob/5f11b52c22aaa33b0711fa85fdadb8300f11b6c1/src/backend.py#L78-L92

**Comment by youmi-zym** [comment]
Hi @lvmingzhe,

You are right, there is a typo and I fix it. As for line 84, it detects whether nearby frame pairs have high covisibility. It improves the SLAM system in rejecting negative loop closures.

Best,
Youmin
