### ISSUE TITLE
Eigen::SparseMatrix error

### ISSUE THREAD

**Issue by yadingHuang** [youmi-zym/GO-SLAM#26]
I couldn't find the Eigen code in the thirdparty directory, so I changed the Eigen path in setup.py to my own path:
include_dirs=[osp.join(ROOT, '/usr/local/include/eigen')].
However, it seems there were errors about Eigen during compilation:
GO-SLAM-main/src/lib/droid_kernels.cu(1176): error: no instance of constructor "SparseBlock::SparseBlock" matches the argument list
            argument types are: (const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::SparseMatrix<double, 0, int>, const Eigen::SparseMatrix<double, 0, int>>, <error-type>, const int, const int)
GO-SLAM-main/src/lib/droid_kernels.cu(1185): error: identifier "b" is undefined

**Comment by youmi-zym** [comment]
Hi,

Maybe you can try to download our repo with 'git clone --recursive https://github.com/youmi-zym/GO-SLAM' rather than 'git clone https://github.com/youmi-zym/GO-SLAM'. Then you will get the Eigen in the third-party directory.

Best, 
Youmin
