### ISSUE TITLE
about rgbd mode's est_pose and gt_pose

### ISSUE THREAD

**Issue by llianxu** [youmi-zym/GO-SLAM#27]
Hello, thank you for this great work. I have encountered a problem where, in RGB mode, I replaced the pose used during the mapping process with the GT pose. The code is as follows
```                     
gt_color, gt_depth,  _, c2w, gt_c2w, mask = unvisit_frame[frame]
batch_rays_o, batch_rays_d, batch_gt_depth, batch_gt_color = build_rays(
     0, H, 0, W, n_rays_unvisit, H, W, fx, fy, cx, cy, gt_c2w, gt_depth, gt_color, self.device,
     nerf_coordinate=False, dir_normalize=False, mask=mask
)
```
```
gt_color, gt_depth,  _, c2w, gt_c2w, mask = visit_frame[frame]
batch_rays_o, batch_rays_d, batch_gt_depth, batch_gt_color = build_rays(
    0, H, 0, W, n_rays, H, W, fx, fy, cx, cy, gt_c2w, gt_depth, gt_color, self.device,
    nerf_coordinate=False, dir_normalize=False, mask=mask
)
```
but the reconstructed mesh is poor.
![image](https://github.com/youmi-zym/GO-SLAM/assets/62802504/7ca1db6e-d6e4-486e-a211-b1674a902023)
May I ask if you have any suggestions？

Thanks

**Comment by youmi-zym** [comment]
Hi,

Thanks for your attention to our work! Before digging into what happened, I'd like to know the results with the estimated poses. Just to make sure other parts are correct.

Best,
Youmin

**Comment by llianxu** [comment]
Hi,
Thanks for your response！I have solved this problem. But I have another question. When I test on replica office0, mono mode's ATE metric is better than rgbd mode.  Do you have some idea about it?

**Comment by youmi-zym** [comment]
Hi,

Great!

I don't know and didn't notice this before. Nevertheless, Replica is quite an easy dataset, so your findings do not surprise me so much. Anyway, please let me know if you face this in other datasets.

Best,
Youmin

**Comment by llianxu** [comment]
Thank you very much，I will test on other dataset.
