### ISSUE TITLE
The trajectory can't match it

### ISSUE THREAD

**Issue by jiaodeshou** [youmi-zym/GO-SLAM#28]
Hello, I am trying to reproduce on the rpelica dataset, but I have encountered an error, indicating that traj_ref and traj_est cannot be aligned, have you ever encountered this situation? How to solve it?
![1704356640211](https://github.com/youmi-zym/GO-SLAM/assets/150789081/68e19427-72ac-414b-9957-2ee9aa380127)

**Comment by jiaodeshou** [comment]
I tried to print out two tracks and found that traj_est showed that the camera moved 0M, that is, no movement

**Comment by youmi-zym** [comment]
Hi, 

I'm sorry for not getting back to you sooner. I don't know what happened. But maybe you can try to debug it by setting the mapping and mesh triggered in lines: https://github.com/youmi-zym/GO-SLAM/blob/main/src/slam.py#L379C15-L379C15. That is: 

```
self.only_tracking=False
mp.Process(target=self.mapping, args=(3, not dont_run)),
mp.Process(target=self.meshing, args=(4,  not dont_run)),
```

Then you can check the system by viewing the generated mesh.

Best,
Youmin

**Comment by jiaodeshou** [comment]
&nbsp; Thank you very much for your reply. I once sent many emails to the author, and you were the only one who replied to me, which touched me very much. I tried to run it under windows before, so there was a problem.
I will try to fix this problem according to your guidance, and now I am trying to reproduce it under ubuntu. If I encounter new problems, I may have to bother you again. Thanks again for your reply, which means a lot to me!

&nbsp; 非常感谢您的回复，我曾经发送过很多邮件给作者，您是唯一回复我的人，这让我非常感动，之前我是在windows下尝试复现的，所以出现了问题。
&nbsp; 我将按照您的指导尝试着去修复这个问题，目前我正在尝试在ubuntu下复现，如果我遇到了新的问题，也许又要叨扰您了，再次感谢您对我的回复，这对我意义重大！


Best，
远在时间另一城市的梓浩
Far away time another city of Zihao


时移世易丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "youmi-zym/GO-SLAM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月8日(星期一) 晚上7:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [youmi-zym/GO-SLAM] The trajectory can't match it (Issue #28)





 
Hi,
 
I'm sorry for not getting back to you sooner. I don't know what happened. But maybe you can try to debug it by setting the mapping and mesh triggered in lines: https://github.com/youmi-zym/GO-SLAM/blob/main/src/slam.py#L379C15-L379C15. That is:
 self.only_tracking=False mp.Process(target=self.mapping, args=(3, not dont_run)), mp.Process(target=self.meshing, args=(4,  not dont_run)),  
Then you can check the system by viewing the generated mesh.
 
Best,
 Youmin

**Comment by youmi-zym** [comment]
Hi,

Cool, no problem!

Best,
Youmin
