### ISSUE TITLE
Was the tracking process using the mapping result?

### ISSUE THREAD

**Issue by nnop** [youmi-zym/GO-SLAM#29]
Great work and amazing results!
I have a question about how the mapping result, which is the implicit surface, was used for tracking.
I didn't find that in the paper.

**Comment by youmi-zym** [comment]
Hi,

We didn't let the results from mapping feedback to tracking. The Mapping is only used for better visualization, i.e., mesh rather than point cloud. But you can take a try to build the interaction between mapping and tracking. 

Best,
Youmin

**Comment by nnop** [comment]
In that way, the method is just a simple loosely combining of DROID-SLAM and neural surface mapping?

**Comment by youmi-zym** [comment]
Hi,

No, the main problem we want to solve is how to build **globally consistent** 3D reconstruction. So, the key is how to globally optimize the pose graph and instantly update the 3D map.

Best,
Youmin

**Comment by nnop** [comment]
Thanks for your explaination.
