### ISSUE TITLE
Insufficient GPU video memory error

### ISSUE THREAD

**Issue by jiaodeshou** [youmi-zym/GO-SLAM#30]
Dear author, 
  I tried to run it on my own computer, and everything went well until it showed that my computer's GPU video memory was insufficient and an error was reported. 
  I also checked your reply to others, you said that at least 12G video memory is required, and my computer is 3070 8G version. Can I modify some parameters to reduce the demand? After all, Gpus are expensive.
Sorry to disturb you during your busy schedule. Looking forward to your reply

zihao
![E027F318483913C81BD1BE053562D9D8](https://github.com/youmi-zym/GO-SLAM/assets/150789081/46d001fd-9167-4a30-8656-d5c767f07077)

**Comment by jiaodeshou** [comment]
Hello, I have solved this problem, I rented a server to run it, and it ran successfully! One more question I have is, how is the video generated for your GO-SLAM homepage? I'd like to learn, if you'll allow me

**Comment by youmi-zym** [comment]
Hi,

Thanks for your interest! You can generate the video by running this on scannet dataset:

`./generate_video_on_scannet.sh rgbd first_try_on_video
`
Furthermore, the predicted mesh on the replica is already a 3D model with color. If not on your side, maybe you can check again.

Best,
Youmin
