### ISSUE TITLE
Thank you for providing such an excellent project. May I ask how to test my dataset

### ISSUE THREAD

**Issue by wahiahia** [youmi-zym/GO-SLAM#4]

**Comment by youmi-zym** [comment]
Hi,

You can organize the record video sequence as the data structure of Replica or Scannet, and run our slam in monocular, rgbd, or stereo mode.

The simplest way, for example in monocular mode, is to extract frames from the video sequence and put them in a folder in order, and also, you need to know the intrinsic.  For the bounding box, you can set a quite large value, such as [[-10, 10], [-10, 10], [-10, 10]]. 

As our slam reports the real bounding box value of the scene when running, you want to get a more accurate result if you change the bounding box accordingly and give a second run.

Best, 
Youmin

**Comment by youmi-zym** [comment]
Hi,

Yes, for the pose, it's used only for evaluation. You can just set [this flag](https://github.com/youmi-zym/GO-SLAM/blob/main/src/slam.py#L303) to False and set all poses to the identity matrix.

Best,
Youmin

**Comment by jiaodeshou** [comment]
Hello, may I ask you to solve the problem of positioning error in running custom data? Could you tell me how to solve it?

**Comment by Santasu28** [comment]
> Hi,
> 
> You can organize the record video sequence as the data structure of Replica or Scannet, and run our slam in monocular, rgbd, or stereo mode.
> 
> The simplest way, for example in monocular mode, is to extract frames from the video sequence and put them in a folder in order, and also, you need to know the intrinsic. For the bounding box, you can set a quite large value, such as [[-10, 10], [-10, 10], [-10, 10]].
> 
> As our slam reports the real bounding box value of the scene when running, you will get a more accurate result if you change the bounding box accordingly and give a second run.
> 
> Best, Youmin

Hi，Youmin

I have a set of image sequences as my dataset, how can I obtain the corresponding mesh file (. ply) of my dataset like the replica dataset？
Looking forward to your reply！
