### ISSUE TITLE
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.

### ISSUE THREAD

**Issue by Promethe-us** [youmi-zym/GO-SLAM#5]
Thanks for providing such a grat work, I follow the README.md and run `./evaluate_on_replica.sh rgbd first_try`:

But I meet:

`Tracking Done!
Start post-processing on mapping...
Full Bundle Adjustment Done!
Multiview Filtering Done!
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 24202.56it/s]
Dense Mapping Done!
Initialized new /home/wuke/.evo/settings.json
#################### Results for /data/wuke/DATA/Replica ...
Traceback (most recent call last):
  File "run.py", line 90, in <module>
    slam.terminate(rank=-1, stream=dataset)
  File "/data/wuke/workspace/GO-SLAM/src/slam.py", line 314, in terminate
    camera_trajectory = self.traj_filler(stream)  # w2cs
  File "/home/wuke/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/wuke/workspace/GO-SLAM/src/trajectory_filler.py", line 107, in __call__
    return lietorch.cat(pose_list, dim=0)
  File "/home/wuke/anaconda3/envs/go-slam/lib/python3.7/site-packages/lietorch-0.2-py3.7-linux-x86_64.egg/lietorch/groups.py", line 315, in cat
    data = torch.cat([X.data for X in group_list], dim=dim)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, AutocastCPU, Autocast, Batched, VmapMode, Functionalize].

CPU: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/build/aten/src/ATen/RegisterCPU.cpp:21063 [kernel]
CUDA: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/build/aten/src/ATen/RegisterCUDA.cpp:29726 [kernel]
QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/build/aten/src/ATen/RegisterQuantizedCPU.cpp:1258 [kernel]
BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradLazy: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradXPU: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradMLC: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradNestedTensor: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/VariableType_3.cpp:11380 [autograd kernel]
Tracer: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/torch/csrc/autograd/generated/TraceType_3.cpp:11220 [kernel]
AutocastCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/autocast_mode.cpp:461 [backend fallback]
Autocast: fallthrough registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/BatchingRegistrations.cpp:1059 [backend fallback]
VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
Functionalize: registered at /opt/conda/conda-bld/pytorch_1646755953518/work/aten/src/ATen/FunctionalizeFallbackKernel.cpp:52 [backend fallback]

office2 done!
Results for all scenes are:

For office2:
cat: /data/wuke/workspace/GO-SLAM/output/1020/office2/first_test/metrics_traj.txt: No such file or directory

cat: /data/wuke/workspace/GO-SLAM/output/1020/office2/first_test/metrics_mesh.txt: No such file or directory
cat: /data/wuke/workspace/GO-SLAM/output/1020/office2/first_test/metrics_traj.txt: No such file or directory
cat: /data/wuke/workspace/GO-SLAM/output/1020/office2/first_test/metrics_mesh.txt: No such file or directory
All Done!`

**Comment by youmi-zym** [comment]
Hi,

So, if I understand correctly, the installation is good, but you still face this problem on office2 after running our code on office0 and office1?

Best,
Youmin

**Comment by Promethe-us** [comment]
Thanks for your reply, I found I set the datapath incorrectly, I correct them and it works, thank you!

**Comment by minhaijun** [comment]
> 感谢您的回复，我发现我设置的数据路径不正确，我纠正了它们，它有效，谢谢！

博主，我也遇到了这样的问题，应该怎么解决呀
