### ISSUE TITLE
How to get "metrics_traj.txt" and "summary.txt"?

### ISSUE THREAD

**Issue by xuyansong99** [youmi-zym/GO-SLAM#7]
Thank you so much for your open source work.
However, I have encountered some problems following your instructions. After modifying the `OUT_DIR` and downloading the `cull_replica_meshv2`, I run `./evaluate_on_replica.sh rgbd first_try`. There are errors about `not found "metrics_traj.txt" and "summary.txt"`.
I have no idea about dealing with this problem. Are these two files generated by running something? Or where to download them from?

**Comment by youmi-zym** [comment]
Hi,

Thanks for your interest in our work. 

Please check the OUT_DIR, you will find metrics_traj.txt and summary.txt.

Basically, if the slam succeeds on any scene, we will evaluate the mesh and trajectory immediately. That means you will get metrics_traj.txt for each scene. There are 8 scenes on the Replica dataset. To get the average metrics, we will collect the results of all scenes in one file, i.e., summary.txt for computation convenience.

Best,
Youmin

**Comment by xuyansong99** [comment]
Yeah, you are right. I have found the reason why occured the problem. 

I ever ignored the previous information in the log prompt, which was I have some errors running the `run.py`. That is why I coud not find metrics_traj.txt and summary.txt.

Fortunately, I was able to run and evaluate successfully, after I reconfigured the runtime enviroment.

**Comment by youmi-zym** [comment]
Hi,

Congrats!

**Comment by wangt-tong** [comment]
> 是的，你是对的。我已经找到了出现问题的原因。
> 
> 我曾经忽略日志提示中的先前信息，即我在运行 .这就是为什么我找不到metrics_traj.txt和摘要的原因.txt。`run.py`
> 
> 幸运的是，在我重新配置运行时环境后，我能够成功运行和评估。

![2023-11-13 13-07-15 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/54926133/a63e7c39-af6d-4f55-85f6-6fe3454a60b0)

**Comment by wangt-tong** [comment]
> 是的，你是对的。我已经找到了出现问题的原因。
> 
> 我曾经忽略日志提示中的先前信息，即我在运行 .这就是为什么我找不到metrics_traj.txt和摘要的原因.txt。`run.py`
> 
> 幸运的是，在我重新配置运行时环境后，我能够成功运行和评估。

Hello, can you share the following of your configuration, I still can't run, the error is as follows
![2023-11-13 13-07-15 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/54926133/5f85b5e1-99bb-42db-9b28-40b11d0f5054)
