### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by sx123456123** [youmi-zym/GO-SLAM#9]
ImportError: /home/suixin/anaconda3/envs/go-slam/lib/python3.7/site-packages/tinycudann_bindings/_61_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE
office0 done!

![2023-10-28 00-09-06 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/66521231/3b328b00-3de4-4c75-9a96-1a2006b723fb)

**Comment by sx123456123** [comment]
I run it successfully, but encounter another problem with GTX 1060:
![2023-10-28 21-11-05 的屏幕截图](https://github.com/youmi-zym/GO-SLAM/assets/66521231/efee0cef-7da7-4518-9b7b-856d0147ced2)

**Comment by glaciomarine** [comment]
> 我成功运行了它，但在 GTX 1060 上遇到了另一个问题： ![2023-10-28 21-11-05 的屏幕截图](https://user-images.githubusercontent.com/66521231/278815357-efee0cef-7da7-4518-9b7b-856d0147ced2.png)

Hello, can I ask you how to install tiny-cuda-nn

**Comment by youmi-zym** [comment]
Hi,

I think it's not a good idea to run our slam on GTX 1060 because the minimum GPU memory requirement is 16G. But, yes, for some sequences, our slam only needs near 12G. But please, use a much more powerful GPU. I know it's hard sometimes.

Best,
Youmin

**Comment by wangt-tong** [comment]
> ImportError: /home/suixin/anaconda3/envs/go-slam/lib/python3.7/site-packages/tinycudann_bindings/_61_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE office0 done!
> 
> ![2023-10-28 00-09-06 的屏幕截图](https://user-images.githubusercontent.com/66521231/278700019-3b328b00-3de4-4c75-9a96-1a2006b723fb.png)
HI : How to solve this problem (For office0:cat: /home/wangt/exps/goslam/Replica/office0/first_try/metrics_traj.txt: 没有那个文件或目录),looking forward to your reply . thanks

**Comment by byronsit** [comment]
> Hi,
> 
> I think it's not a good idea to run our slam on GTX 1060 because the minimum GPU memory requirement is 16G. But, yes, for some sequences, our slam only needs near 12G. But please, use a much more powerful GPU. I know it's hard sometimes.
> 
> Best, Youmin

in GTX4080-16G version, it shows that "CUDA out of memory." QAQ
